// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: rpc/domain/field.proto

package domain

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_rpc_domain_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_rpc_domain_field_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Captcha struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Captcha) Reset() {
	*x = Captcha{}
	mi := &file_rpc_domain_field_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Captcha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Captcha) ProtoMessage() {}

func (x *Captcha) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_field_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Captcha.ProtoReflect.Descriptor instead.
func (*Captcha) Descriptor() ([]byte, []int) {
	return file_rpc_domain_field_proto_rawDescGZIP(), []int{1}
}

func (x *Captcha) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Mobile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Mobile) Reset() {
	*x = Mobile{}
	mi := &file_rpc_domain_field_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mobile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mobile) ProtoMessage() {}

func (x *Mobile) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_field_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mobile.ProtoReflect.Descriptor instead.
func (*Mobile) Descriptor() ([]byte, []int) {
	return file_rpc_domain_field_proto_rawDescGZIP(), []int{2}
}

func (x *Mobile) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_rpc_domain_field_proto protoreflect.FileDescriptor

var file_rpc_domain_field_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x6f, 0x1a, 0x1b, 0x62, 0x75,
	0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x02, 0x49, 0x44, 0x12,
	0x1d, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07,
	0xba, 0x48, 0x04, 0x22, 0x02, 0x28, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33,
	0x0a, 0x07, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x28, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x12, 0xba, 0x48, 0x0f, 0x72, 0x0d, 0x32,
	0x08, 0x5e, 0x5b, 0x30, 0x2d, 0x39, 0x5d, 0x2a, 0x24, 0x98, 0x01, 0x04, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x3e, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x34, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1e, 0xba, 0x48,
	0x1b, 0x72, 0x19, 0x32, 0x14, 0x5e, 0x28, 0x31, 0x5b, 0x33, 0x2d, 0x39, 0x5d, 0x5b, 0x30, 0x2d,
	0x39, 0x5d, 0x5c, 0x64, 0x7b, 0x38, 0x7d, 0x29, 0x24, 0x98, 0x01, 0x0b, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x31, 0x30,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_domain_field_proto_rawDescOnce sync.Once
	file_rpc_domain_field_proto_rawDescData = file_rpc_domain_field_proto_rawDesc
)

func file_rpc_domain_field_proto_rawDescGZIP() []byte {
	file_rpc_domain_field_proto_rawDescOnce.Do(func() {
		file_rpc_domain_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_domain_field_proto_rawDescData)
	})
	return file_rpc_domain_field_proto_rawDescData
}

var file_rpc_domain_field_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_domain_field_proto_goTypes = []any{
	(*ID)(nil),      // 0: vo.ID
	(*Captcha)(nil), // 1: vo.Captcha
	(*Mobile)(nil),  // 2: vo.Mobile
}
var file_rpc_domain_field_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_domain_field_proto_init() }
func file_rpc_domain_field_proto_init() {
	if File_rpc_domain_field_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_domain_field_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_domain_field_proto_goTypes,
		DependencyIndexes: file_rpc_domain_field_proto_depIdxs,
		MessageInfos:      file_rpc_domain_field_proto_msgTypes,
	}.Build()
	File_rpc_domain_field_proto = out.File
	file_rpc_domain_field_proto_rawDesc = nil
	file_rpc_domain_field_proto_goTypes = nil
	file_rpc_domain_field_proto_depIdxs = nil
}
