// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc/user.proto

package rpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	rpc "demo1/rpc"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserName is the fully-qualified name of the User service.
	UserName = "rpc.User"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserGetProcedure is the fully-qualified name of the User's Get RPC.
	UserGetProcedure = "/rpc.User/Get"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	userServiceDescriptor   = rpc.File_rpc_user_proto.Services().ByName("User")
	userGetMethodDescriptor = userServiceDescriptor.Methods().ByName("Get")
)

// UserClient is a client for the rpc.User service.
type UserClient interface {
	Get(context.Context, *connect.Request[rpc.UserGetRequest]) (*connect.Response[rpc.UserGetResponse], error)
}

// NewUserClient constructs a client for the rpc.User service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &userClient{
		get: connect.NewClient[rpc.UserGetRequest, rpc.UserGetResponse](
			httpClient,
			baseURL+UserGetProcedure,
			connect.WithSchema(userGetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// userClient implements UserClient.
type userClient struct {
	get *connect.Client[rpc.UserGetRequest, rpc.UserGetResponse]
}

// Get calls rpc.User.Get.
func (c *userClient) Get(ctx context.Context, req *connect.Request[rpc.UserGetRequest]) (*connect.Response[rpc.UserGetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// UserHandler is an implementation of the rpc.User service.
type UserHandler interface {
	Get(context.Context, *connect.Request[rpc.UserGetRequest]) (*connect.Response[rpc.UserGetResponse], error)
}

// NewUserHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserHandler(svc UserHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userGetHandler := connect.NewUnaryHandler(
		UserGetProcedure,
		svc.Get,
		connect.WithSchema(userGetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc.User/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserGetProcedure:
			userGetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserHandler returns CodeUnimplemented from all methods.
type UnimplementedUserHandler struct{}

func (UnimplementedUserHandler) Get(context.Context, *connect.Request[rpc.UserGetRequest]) (*connect.Response[rpc.UserGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.User.Get is not implemented"))
}
