// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: rpc/domain/user/field.proto

package user

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Age struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Age) Reset() {
	*x = Age{}
	mi := &file_rpc_domain_user_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Age) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Age) ProtoMessage() {}

func (x *Age) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_user_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Age.ProtoReflect.Descriptor instead.
func (*Age) Descriptor() ([]byte, []int) {
	return file_rpc_domain_user_field_proto_rawDescGZIP(), []int{0}
}

func (x *Age) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Amount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_rpc_domain_user_field_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_user_field_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_rpc_domain_user_field_proto_rawDescGZIP(), []int{1}
}

func (x *Amount) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Avatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Avatar) Reset() {
	*x = Avatar{}
	mi := &file_rpc_domain_user_field_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Avatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avatar) ProtoMessage() {}

func (x *Avatar) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_user_field_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avatar.ProtoReflect.Descriptor instead.
func (*Avatar) Descriptor() ([]byte, []int) {
	return file_rpc_domain_user_field_proto_rawDescGZIP(), []int{2}
}

func (x *Avatar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Bio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Bio) Reset() {
	*x = Bio{}
	mi := &file_rpc_domain_user_field_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bio) ProtoMessage() {}

func (x *Bio) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_user_field_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bio.ProtoReflect.Descriptor instead.
func (*Bio) Descriptor() ([]byte, []int) {
	return file_rpc_domain_user_field_proto_rawDescGZIP(), []int{3}
}

func (x *Bio) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HashID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *HashID) Reset() {
	*x = HashID{}
	mi := &file_rpc_domain_user_field_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashID) ProtoMessage() {}

func (x *HashID) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_user_field_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashID.ProtoReflect.Descriptor instead.
func (*HashID) Descriptor() ([]byte, []int) {
	return file_rpc_domain_user_field_proto_rawDescGZIP(), []int{4}
}

func (x *HashID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Level struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Level) Reset() {
	*x = Level{}
	mi := &file_rpc_domain_user_field_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_user_field_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_rpc_domain_user_field_proto_rawDescGZIP(), []int{5}
}

func (x *Level) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Nickname struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Nickname) Reset() {
	*x = Nickname{}
	mi := &file_rpc_domain_user_field_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nickname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nickname) ProtoMessage() {}

func (x *Nickname) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_user_field_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nickname.ProtoReflect.Descriptor instead.
func (*Nickname) Descriptor() ([]byte, []int) {
	return file_rpc_domain_user_field_proto_rawDescGZIP(), []int{6}
}

func (x *Nickname) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Password struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Password) Reset() {
	*x = Password{}
	mi := &file_rpc_domain_user_field_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_domain_user_field_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_rpc_domain_user_field_proto_rawDescGZIP(), []int{7}
}

func (x *Password) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_rpc_domain_user_field_proto protoreflect.FileDescriptor

var file_rpc_domain_user_field_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x26, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x09, 0xba, 0x48, 0x06, 0x22, 0x04, 0x18, 0x78, 0x28,
	0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4e, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x12, 0x44, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x2e, 0xba, 0x48, 0x2b, 0x72, 0x29, 0x32, 0x27, 0x5e, 0x28, 0x2e, 0x2a, 0x29, 0x5c,
	0x2e, 0x28, 0x6a, 0x70, 0x67, 0x7c, 0x67, 0x69, 0x66, 0x7c, 0x69, 0x63, 0x6f, 0x7c, 0x70, 0x63,
	0x78, 0x7c, 0x6a, 0x70, 0x65, 0x67, 0x7c, 0x70, 0x6e, 0x67, 0x7c, 0x77, 0x65, 0x62, 0x70, 0x29,
	0x24, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x03, 0x42, 0x69, 0x6f, 0x12,
	0x1e, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08,
	0xba, 0x48, 0x05, 0x72, 0x03, 0x18, 0xc8, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x35, 0x0a, 0x06, 0x48, 0x61, 0x73, 0x68, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x15, 0xba, 0x48, 0x12, 0x72, 0x10, 0x32,
	0x0e, 0x5e, 0x5b, 0x61, 0x2d, 0x7a, 0x41, 0x2d, 0x5a, 0x30, 0x2d, 0x39, 0x5d, 0x2a, 0x24, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x23, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0d,
	0xba, 0x48, 0x0a, 0x22, 0x08, 0x30, 0x00, 0x30, 0x0a, 0x30, 0x14, 0x30, 0x1e, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x10, 0x02, 0x18, 0x0a, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x2b, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48,
	0x06, 0x72, 0x04, 0x10, 0x06, 0x18, 0x14, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x1b,
	0x5a, 0x19, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x31, 0x30, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_domain_user_field_proto_rawDescOnce sync.Once
	file_rpc_domain_user_field_proto_rawDescData = file_rpc_domain_user_field_proto_rawDesc
)

func file_rpc_domain_user_field_proto_rawDescGZIP() []byte {
	file_rpc_domain_user_field_proto_rawDescOnce.Do(func() {
		file_rpc_domain_user_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_domain_user_field_proto_rawDescData)
	})
	return file_rpc_domain_user_field_proto_rawDescData
}

var file_rpc_domain_user_field_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_domain_user_field_proto_goTypes = []any{
	(*Age)(nil),      // 0: user.Age
	(*Amount)(nil),   // 1: user.Amount
	(*Avatar)(nil),   // 2: user.Avatar
	(*Bio)(nil),      // 3: user.Bio
	(*HashID)(nil),   // 4: user.HashID
	(*Level)(nil),    // 5: user.Level
	(*Nickname)(nil), // 6: user.Nickname
	(*Password)(nil), // 7: user.Password
}
var file_rpc_domain_user_field_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_domain_user_field_proto_init() }
func file_rpc_domain_user_field_proto_init() {
	if File_rpc_domain_user_field_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_domain_user_field_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_domain_user_field_proto_goTypes,
		DependencyIndexes: file_rpc_domain_user_field_proto_depIdxs,
		MessageInfos:      file_rpc_domain_user_field_proto_msgTypes,
	}.Build()
	File_rpc_domain_user_field_proto = out.File
	file_rpc_domain_user_field_proto_rawDesc = nil
	file_rpc_domain_user_field_proto_goTypes = nil
	file_rpc_domain_user_field_proto_depIdxs = nil
}
