// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: rpc/response/user.proto

package response

import (
	_ "chapter10/rpc/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         *int64                 `protobuf:"varint,1,opt,name=ID,proto3,oneof" json:"ID,omitempty"`
	HashID     *string                `protobuf:"bytes,2,opt,name=HashID,proto3,oneof" json:"HashID,omitempty"`
	Mobile     *string                `protobuf:"bytes,3,opt,name=Mobile,proto3,oneof" json:"Mobile,omitempty"`
	Age        *int64                 `protobuf:"varint,4,opt,name=Age,proto3,oneof" json:"Age,omitempty"`
	Level      *int64                 `protobuf:"varint,5,opt,name=Level,proto3,oneof" json:"Level,omitempty"`
	LevelDesc  *string                `protobuf:"bytes,6,opt,name=LevelDesc,proto3,oneof" json:"LevelDesc,omitempty"`
	Nickname   *string                `protobuf:"bytes,7,opt,name=Nickname,proto3,oneof" json:"Nickname,omitempty"`
	Avatar     *string                `protobuf:"bytes,8,opt,name=Avatar,proto3,oneof" json:"Avatar,omitempty"`
	Bio        *string                `protobuf:"bytes,9,opt,name=Bio,proto3,oneof" json:"Bio,omitempty"`
	Amount     *float64               `protobuf:"fixed64,10,opt,name=Amount,proto3,oneof" json:"Amount,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=CreateTime,proto3,oneof" json:"CreateTime,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_rpc_response_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_rpc_response_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetID() int64 {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return 0
}

func (x *User) GetHashID() string {
	if x != nil && x.HashID != nil {
		return *x.HashID
	}
	return ""
}

func (x *User) GetMobile() string {
	if x != nil && x.Mobile != nil {
		return *x.Mobile
	}
	return ""
}

func (x *User) GetAge() int64 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *User) GetLevel() int64 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *User) GetLevelDesc() string {
	if x != nil && x.LevelDesc != nil {
		return *x.LevelDesc
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *User) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *User) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type UserOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *UserOne) Reset() {
	*x = UserOne{}
	mi := &file_rpc_response_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOne) ProtoMessage() {}

func (x *UserOne) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOne.ProtoReflect.Descriptor instead.
func (*UserOne) Descriptor() ([]byte, []int) {
	return file_rpc_response_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserOne) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserMany struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*User `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *UserMany) Reset() {
	*x = UserMany{}
	mi := &file_rpc_response_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMany) ProtoMessage() {}

func (x *UserMany) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMany.ProtoReflect.Descriptor instead.
func (*UserMany) Descriptor() ([]byte, []int) {
	return file_rpc_response_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserMany) GetList() []*User {
	if x != nil {
		return x.List
	}
	return nil
}

type UserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *UserLogin) Reset() {
	*x = UserLogin{}
	mi := &file_rpc_response_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogin) ProtoMessage() {}

func (x *UserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogin.ProtoReflect.Descriptor instead.
func (*UserLogin) Descriptor() ([]byte, []int) {
	return file_rpc_response_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserLogin) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserSmsRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *UserSmsRegister) Reset() {
	*x = UserSmsRegister{}
	mi := &file_rpc_response_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSmsRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSmsRegister) ProtoMessage() {}

func (x *UserSmsRegister) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSmsRegister.ProtoReflect.Descriptor instead.
func (*UserSmsRegister) Descriptor() ([]byte, []int) {
	return file_rpc_response_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserSmsRegister) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *UserRegister) Reset() {
	*x = UserRegister{}
	mi := &file_rpc_response_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegister) ProtoMessage() {}

func (x *UserRegister) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegister.ProtoReflect.Descriptor instead.
func (*UserRegister) Descriptor() ([]byte, []int) {
	return file_rpc_response_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserRegister) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserModify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserModify) Reset() {
	*x = UserModify{}
	mi := &file_rpc_response_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModify) ProtoMessage() {}

func (x *UserModify) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModify.ProtoReflect.Descriptor instead.
func (*UserModify) Descriptor() ([]byte, []int) {
	return file_rpc_response_user_proto_rawDescGZIP(), []int{6}
}

type UserCash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserCash) Reset() {
	*x = UserCash{}
	mi := &file_rpc_response_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCash) ProtoMessage() {}

func (x *UserCash) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCash.ProtoReflect.Descriptor instead.
func (*UserCash) Descriptor() ([]byte, []int) {
	return file_rpc_response_user_proto_rawDescGZIP(), []int{7}
}

var File_rpc_response_user_proto protoreflect.FileDescriptor

var file_rpc_response_user_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0x16, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x03, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x13, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x02, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x48, 0x61,
	0x73, 0x68, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x48, 0x61,
	0x73, 0x68, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x03, 0x52, 0x03, 0x41, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x04, 0x52, 0x05, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x44,
	0x65, 0x73, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x05, 0x52, 0x09, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x4e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x06, 0x52, 0x08, 0x4e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x07, 0x52, 0x06, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x42, 0x69, 0x6f, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x08, 0x52, 0x03, 0x42, 0x69, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x1b,
	0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x48, 0x09,
	0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x3f, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x0a, 0x52, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03,
	0x5f, 0x49, 0x44, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x48, 0x61, 0x73, 0x68, 0x49, 0x44, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x41, 0x67,
	0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x4e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x42, 0x69, 0x6f, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x65, 0x12, 0x22,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x22, 0x2e, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x22,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x2f, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x22, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6d, 0x73, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x0c, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x22, 0x0c,
	0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x22, 0x0a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x73, 0x68, 0x42, 0x18, 0x5a, 0x16, 0x63, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x31, 0x30, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_response_user_proto_rawDescOnce sync.Once
	file_rpc_response_user_proto_rawDescData = file_rpc_response_user_proto_rawDesc
)

func file_rpc_response_user_proto_rawDescGZIP() []byte {
	file_rpc_response_user_proto_rawDescOnce.Do(func() {
		file_rpc_response_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_response_user_proto_rawDescData)
	})
	return file_rpc_response_user_proto_rawDescData
}

var file_rpc_response_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_response_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: response.User
	(*UserOne)(nil),               // 1: response.UserOne
	(*UserMany)(nil),              // 2: response.UserMany
	(*UserLogin)(nil),             // 3: response.UserLogin
	(*UserSmsRegister)(nil),       // 4: response.UserSmsRegister
	(*UserRegister)(nil),          // 5: response.UserRegister
	(*UserModify)(nil),            // 6: response.UserModify
	(*UserCash)(nil),              // 7: response.UserCash
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_rpc_response_user_proto_depIdxs = []int32{
	8, // 0: response.User.CreateTime:type_name -> google.protobuf.Timestamp
	0, // 1: response.UserOne.User:type_name -> response.User
	0, // 2: response.UserMany.List:type_name -> response.User
	0, // 3: response.UserLogin.User:type_name -> response.User
	0, // 4: response.UserSmsRegister.User:type_name -> response.User
	0, // 5: response.UserRegister.User:type_name -> response.User
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_rpc_response_user_proto_init() }
func file_rpc_response_user_proto_init() {
	if File_rpc_response_user_proto != nil {
		return
	}
	file_rpc_response_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_response_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_response_user_proto_goTypes,
		DependencyIndexes: file_rpc_response_user_proto_depIdxs,
		MessageInfos:      file_rpc_response_user_proto_msgTypes,
	}.Build()
	File_rpc_response_user_proto = out.File
	file_rpc_response_user_proto_rawDesc = nil
	file_rpc_response_user_proto_goTypes = nil
	file_rpc_response_user_proto_depIdxs = nil
}
